### ISSUE TITLE
Question (not issue). Did you ever discover a good way while you were writing this to apply color to a range of text over multiple rows?

### ISSUE THREAD

**Issue by LWKlaus** [JatinSanghvi/color-my-text-vscode#4]
For example say you have 3 *** and you want everything over the next lines to be a given color, until *** is encountered again.

Take this:

***
   Item 1   <make this green>
   Item 2  <make this green>
   Item 3  <make this green>
   ....
***
<now back to regular editor colors>

I ask because I'm working on extension where I need to have knowledge of what was on the lines above, and I'm not finding a great way via just implementing the GetClassificationSpans interface  (which just return a line at a time, and not all lines that have not been touched, etc.)

Thanks!  Lee

PS.  It's clear you put a lot of work into this - nicely done!!!

**Comment by JatinSanghvi** [comment]
Hi, this extension only matches text within a line. I did not get the overall context for which you need to match text between two `***`. It should be possible to match text using regex like below, but I am not sure if it will help with your work; I have forgotten everything that had to do with VS code extension development.

```js
const text = `
To be ignored
***
Item A1
Item A2
***
To be ignored
***
Item B1
Item B2
***`;

const regex = /\*\*\*([\s\S]*?)\*\*\*/g;
let matches;
const results = [];

while ((matches = regex.exec(text)) !== null) {
    results.push(matches[1].trim());
}

console.log(results);
```

**Comment by JatinSanghvi** [comment]
Hi, this extension only matches text within a line. I did not get the overall context for which you need to match text between two `***`. It should be possible to match text using regex like below, but I am not sure if it will help with your work; I have forgotten everything that had to do with VS code extension development.

```js
const text = `
To be ignored
***
Item A1
Item A2
***
To be ignored
***
Item B1
Item B2
***`;

const regex = /\*\*\*([\s\S]*?)\*\*\*/g;
let matches;
const results = [];

while ((matches = regex.exec(text)) !== null) {
    results.push(matches[1].trim());
}

console.log(results);
```
